name = "email-management-worker"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "./email-management-app"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
EMAIL_MANAGEMENT_WORKER_CORS_ORIGIN = ""
EMAIL_MANAGEMENT_WORKER_HTTP_TIMEOUT = "20"
EMAIL_MANAGEMENT_WORKER_MAIL_FETCH_LIMIT = "20"
EMAIL_MANAGEMENT_WORKER_LIVE_TOKEN_URL = "https://login.live.com/oauth20_token.srf"
EMAIL_MANAGEMENT_WORKER_MS_TOKEN_URL = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
EMAIL_MANAGEMENT_WORKER_GRAPH_BASE_URL = "https://graph.microsoft.com/v1.0"
EMAIL_MANAGEMENT_WORKER_GOOGLE_CLIENT_ID = ""
EMAIL_MANAGEMENT_WORKER_GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
EMAIL_MANAGEMENT_WORKER_GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
EMAIL_MANAGEMENT_WORKER_GMAIL_API_BASE_URL = "https://gmail.googleapis.com/gmail/v1"
